# Generated by Django 5.0.4 on 2024-04-10 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=256)),
                ('state', models.CharField(choices=[('NSW', 'New South Wales'), ('VIC', 'Victoria'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('WA', 'Western Australia'), ('ACT', 'Australian Capital Territory'), ('NT', 'Northern Territory'), ('TAS', 'Tasmania')], default='NSW', max_length=3)),
                ('city', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='gear',
            name='gigs',
            field=models.ManyToManyField(to='main_app.gig'),
        ),
    ]
